#:schema node_modules/wrangler/config-schema.json
name = "theshook-one-worker"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

routes = [
	{ pattern = "theshook.one/", zone_name = "theshook.one" }
]

workers_dev = false

[placement]
mode = "smart"
